spring.application.name=adcampaign
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ad_campaign_db
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true

